<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Documento sin t&iacute;tulo</title>
<style type="text/css">
<!--
.Estilo1 {font-size: 24px}
-->
</style>
<script type="text/JavaScript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}
//-->
</script>
</head>

<body>
<table width="698" height="380" border="0" align="center" cellspacing="0">
  <tr>
    <td colspan="8" bgcolor="#009966">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="8" bgcolor="#0066FF"><div align="center" class="Estilo1">FROMULARIO DE VENTAS  </div></td>
  </tr>
  <tr>
    <td width="39" bgcolor="#0066FF">&nbsp;</td>
    <td width="124" bgcolor="#0066FF"><div align="right">Nombre Empleado: </div></td>
    <td width="12" bgcolor="#0066FF">&nbsp;</td>
    <td width="159" bgcolor="#0066FF"><form name="form2" id="form2">
      <select name="menu2" onchange="MM_jumpMenu('parent',this,0)">
        <option>unnamed1</option>
      </select>
    </form>      <label></label></td>
    <td width="13" bgcolor="#0066FF"><label></label></td>
    <td width="121" bgcolor="#0066FF"><div align="right">Precio:</div></td>
    <td width="18" bgcolor="#0066FF">&nbsp;</td>
    <td width="196" bgcolor="#0066FF"><label>
      <input type="text" name="textfield" />
    </label></td>
  </tr>
  <tr>
    <td height="21" bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><div align="right"></div></td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><div align="right"></div></td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><div align="right">Nombre Cliente: </div></td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><form name="form1" id="form1">
      <select name="menu1" onchange="MM_jumpMenu('parent',this,0)">
        <option>unnamed1</option>
      </select>
    </form>
    </td>
    <td bgcolor="#0066FF"><label></label></td>
    <td bgcolor="#0066FF"><div align="right">Fecha de Venta: </div></td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><form name="form4" id="form4">
      <select name="menu4" onchange="MM_jumpMenu('parent',this,0)">
        <option>unnamed1</option>
      </select>
    </form>
    </td>
  </tr>
  <tr>
    <td height="21" bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><div align="right"></div></td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><div align="right"></div></td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><div align="right">Servicio:</div></td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><form name="form3" id="form3">
      <select name="menu3" onchange="MM_jumpMenu('parent',this,0)">
        <option>unnamed1</option>
      </select>
    </form>
    </td>
    <td bgcolor="#0066FF"><label></label></td>
    <td bgcolor="#0066FF"><div align="right">Supervisor a Cargo: </div></td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><form name="form5" id="form5">
      <select name="menu5" onchange="MM_jumpMenu('parent',this,0)">
        <option>unnamed1</option>
      </select>
    </form>
    </td>
  </tr>
  <tr>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><div align="right"></div></td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><div align="right"></div></td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
  </tr>
  <tr>
    <td height="47" colspan="8" bgcolor="#0066FF"><div align="center">
      <input type="submit" name="Submit" value="GUARDAR" />
    </div></td>
  </tr>
  <tr>
    <td height="49" colspan="8" bgcolor="#009966"><label></label></td>
  </tr>
</table>
</body>
</html>
