<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Documento sin t&iacute;tulo</title>
<style type="text/css">
<!--
.Estilo1 {font-size: 24px}
-->
</style>
<script type="text/JavaScript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}
//-->
</script>
	<link href="../Bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="../Bootstrap/css/estilos.css" rel="stylesheet">
<style type="text/css">
<!--
body {
	background-image: url(../images/fondoesc.jpeg);
	max-height:auto;
}
-->
</style>
</head>

<body>
<form id="form1" name="form1" method="post" action="validar.php">
  <div align="center">
    <p>&nbsp;</p>
    <p><img src="../images/logo.jpg" width="346" height="154" class="img-circle"/>  </p>
    <p>&nbsp;</p>
  </div>
  <table width="487" height="324" border="0" align="center" cellspacing="0">
  <tr>
    <td colspan="5" bgcolor="#009966">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="5" bgcolor="#0066FF"><div align="center" class="Estilo1">LOGIN </div></td>
  </tr>
  <tr>
    <td width="58" bgcolor="#0066FF">&nbsp;</td>
    <td width="194" bgcolor="#0066FF"><h4><div align="right">Nombre: </div></h4></td>
    <td width="45" bgcolor="#0066FF">&nbsp;</td>
    <td width="189" bgcolor="#0066FF"><label><input name="Nombre" type="text" class="form-control" id="Nombre"
             placeholder="Nombre de Usuario">
    <td width="103" bgcolor="#0066FF"></label>
	
  </tr>
  <tr>
    <td height="21" bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><div align="right"><h4>Contrase&ntilde;a:</h4></div></td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><label>
      <input name="Pass" type="password" class="form-control" id="Pass"
             placeholder="Password">
    </label></td>
    <td bgcolor="#0066FF">&nbsp;</td>
  </tr>
  <tr>
    <td height="27" bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><label></label></td>
  </tr>
  <tr>
    <td height="21" colspan="5" bgcolor="#0066FF"><div align="center">  
	   <input id="submit" name="submit" type="submit" value="Ingresar" class="btn btn-success btn-lg">
        </td>
  </tr>
  <tr>
    <td height="21" colspan="5" bgcolor="#0066FF">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="5" bgcolor="#009966">&nbsp;</td>
  </tr>
</table>
</form>

<p>&nbsp;</p>
	<p>
	  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
	  <script src="js/responsive.js"></script>
	  <script src="js/bootstrap.min.js"></script>
        </p>
</body>
</html>
