<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Documento sin t&iacute;tulo</title>
<style type="text/css">
<!--
.Estilo1 {font-size: 24px}
-->
</style>
<script type="text/JavaScript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}
//-->
</script>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/estilos.css" rel="stylesheet">
</head>
<body>
<form id="form6" name="form6" method="post" action="">
  <table width="698" height="343" border="0" align="center" cellspacing="0">
    <tr>
      <td colspan="8" bgcolor="#009966">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="8" bgcolor="#0066FF"><div align="center" class="Estilo1">FROMULARIO DE VENTAS </div></td>
    </tr>
    <tr>
      <td width="39" bgcolor="#0066FF">&nbsp;</td>
      <td width="124" bgcolor="#0066FF"><div align="right">Venta: </div></td>
      <td width="12" bgcolor="#0066FF">&nbsp;</td>
      <td width="159" bgcolor="#0066FF"><select name="menu2" onchange="MM_jumpMenu('parent',this,0)">
          <option>unnamed1</option>
        </select>
          <label></label></td>
      <td width="13" bgcolor="#0066FF"><label></label></td>
      <td width="121" bgcolor="#0066FF"><div align="right">Fecha:</div></td>
      <td width="18" bgcolor="#0066FF">&nbsp;</td>
      <td width="196" bgcolor="#0066FF"><label>
        <input name="email" type="email" class="form-control" id="ejemplo_email_3"
             placeholder="Fecha de Venta" />
      </label></td>
    </tr>
    <tr>
      <td bgcolor="#0066FF">&nbsp;</td>
      <td bgcolor="#0066FF"><div align="right">Servicio: </div></td>
      <td bgcolor="#0066FF">&nbsp;</td>
      <td bgcolor="#0066FF"><select name="menu1" onchange="MM_jumpMenu('parent',this,0)">
          <option>unnamed1</option>
        </select>
      </td>
      <td bgcolor="#0066FF"><label></label></td>
      <td bgcolor="#0066FF"><div align="right">Usuario: </div></td>
      <td bgcolor="#0066FF">&nbsp;</td>
      <td bgcolor="#0066FF"><select name="menu4" onchange="MM_jumpMenu('parent',this,0)">
          <option>unnamed1</option>
        </select>
      </td>
    </tr>
    <tr>
      <td height="21" bgcolor="#0066FF">&nbsp;</td>
      <td bgcolor="#0066FF"><div align="right"></div></td>
      <td bgcolor="#0066FF">&nbsp;</td>
      <td bgcolor="#0066FF">&nbsp;</td>
      <td bgcolor="#0066FF">&nbsp;</td>
      <td bgcolor="#0066FF"><div align="right"></div></td>
      <td bgcolor="#0066FF">&nbsp;</td>
      <td bgcolor="#0066FF">&nbsp;</td>
    </tr>
    <tr>
      <td bgcolor="#0066FF">&nbsp;</td>
      <td bgcolor="#0066FF"><div align="right">Cliente:</div></td>
      <td bgcolor="#0066FF">&nbsp;</td>
      <td bgcolor="#0066FF"><select name="menu3" onchange="MM_jumpMenu('parent',this,0)">
          <option>unnamed1</option>
        </select>
      </td>
    </tr>
    <tr>
      <td bgcolor="#0066FF">&nbsp;</td>
      <td bgcolor="#0066FF">&nbsp;</td>
      <td bgcolor="#0066FF">&nbsp;</td>
      <td bgcolor="#0066FF">&nbsp;</td>
      <td bgcolor="#0066FF">&nbsp;</td>
      <td bgcolor="#0066FF">&nbsp;</td>
      <td bgcolor="#0066FF">&nbsp;</td>
      <td bgcolor="#0066FF">&nbsp;</td>
    </tr>
    <tr>
      <td height="38" bgcolor="#0066FF">&nbsp;</td>
      <td height="38" bgcolor="#0066FF"><div align="right">Precio:</div></td>
      <td height="38" bgcolor="#0066FF">&nbsp;</td>
      <td height="38" bgcolor="#0066FF"><input name="email" type="email" class="form-control" id="ejemplo_email_3"
             placeholder="Precio de Venta" /></td>
      <td height="38" bgcolor="#0066FF">&nbsp;</td>
      <td height="38" bgcolor="#0066FF"><div align="right">Detalle:</div></td>
      <td height="38" bgcolor="#0066FF">&nbsp;</td>
      <td height="38" bgcolor="#0066FF"><label>
        <input name="email" type="email" class="form-control" id="ejemplo_email_3"
             placeholder="Detalle de Venta" />
      </label></td>
    </tr>
    <tr>
      <td height="21" bgcolor="#0066FF">&nbsp;</td>
      <td height="21" bgcolor="#0066FF">&nbsp;</td>
      <td height="21" bgcolor="#0066FF">&nbsp;</td>
      <td height="21" bgcolor="#0066FF">&nbsp;</td>
      <td height="21" bgcolor="#0066FF">&nbsp;</td>
      <td height="21" bgcolor="#0066FF">&nbsp;</td>
      <td height="21" bgcolor="#0066FF">&nbsp;</td>
      <td height="21" bgcolor="#0066FF">&nbsp;</td>
    </tr>
    <tr>
      <td height="49" colspan="8" bgcolor="#0066FF"><div align="center">
          <button type="button" class="btn btn-primary">Guardar</button>
      </div></td>
    </tr>
    <tr>
      <td height="49" colspan="8" bgcolor="#009966">&nbsp;</td>
    </tr>
  </table>
</form>
	<script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="js/responsive.js"></script>
    <script src="js/bootstrap.min.js"></script>
</body>
</html>
