<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Documento sin t&iacute;tulo</title>
<style type="text/css">
<!--
.Estilo1 {font-size: 24px}
-->
</style>
<script type="text/JavaScript">
<!--
function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}
//-->
</script>
	<link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/estilos.css" rel="stylesheet">
</head>
<body>
<form id="form1" name="form1" method="post" action="">
<table width="574" height="358" border="0" align="center" cellspacing="0">
  <tr>
    <td colspan="7" bgcolor="#009966">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="7" bgcolor="#0066FF"><div align="center" class="Estilo1">REGISTRO CLIENTES </div></td>
  </tr>
  <tr>
    <td width="49" bgcolor="#0066FF">&nbsp;</td>
    <td width="51" bgcolor="#0066FF">&nbsp;</td>
    <td width="133" bgcolor="#0066FF"><div align="right">Nombre: </div></td>
    <td width="22" bgcolor="#0066FF">&nbsp;</td>
    <td width="130" bgcolor="#0066FF">
      <input type="email" class="form-control" id="ejemplo_email_3"
             placeholder="Nombre de Cliente">
	  
    </td>
    <td width="84" bgcolor="#0066FF">&nbsp;</td>
    <td width="79" bgcolor="#0066FF">&nbsp;</td>
    </tr>
  <tr>
    <td height="21" bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    </tr>
  <tr>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><div align="right">Apellido Paterno: </div></td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">
      <input type="email" class="form-control" id="ejemplo_email_3"
             placeholder="Apellido Paterno">
   </td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    </tr>
  <tr>
    <td height="21" bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    </tr>
  <tr>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><div align="right">Apellido Materno:</div></td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">
     <input type="email" class="form-control" id="ejemplo_email_3"
             placeholder="Apellido Materno">
    </td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    </tr>
  <tr>
    <td height="21" bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    </tr>
  <tr>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF"><div align="right">Carnet de Identidad: </div></td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">
      <input type="email" class="form-control" id="ejemplo_email_3"
             placeholder="Carnet de Identidad">
    </td>
    <td bgcolor="#0066FF">&nbsp;</td>
    <td bgcolor="#0066FF">&nbsp;</td>
    </tr>
  <tr>
    <td colspan="7" bgcolor="#0066FF">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="7" bgcolor="#0066FF"><div align="center">
       <button type="button" class="btn btn-primary">Guardar</button>
        </div></td>
  </tr>
  <tr>
    <td colspan="7" bgcolor="#009966">&nbsp;</td>
  </tr>
</table>
</form>
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="js/responsive.js"></script>
    <script src="js/bootstrap.min.js"></script>
</body>
</html>
